### PR TITLE
Adds support for scheduling tasks with Quartz

### PR DESCRIPTION
**Pull request by Manokethan**

### CODE REVIEW

**Comment by mminella** [comment]
I'd rather name this `spring-cloud-scheduler-local` and not tie it to an implementation.  It also makes things a bit confusing since the CF scheduler system is based on Quartz.

**Comment by mminella** [comment]
Is this intended to be an embedded system within the local SCDF server?  If so, why are we using an additional deployer instance here and not calling back to SCDF?

**Comment by Manokethan** [comment]
> Is this intended to be an embedded system within the local SCDF server? If so, why are we using an additional deployer instance here and not calling back to SCDF?

what do you mean by calling SCDF directly? Do you mean by calling the REST API or injecting the TaskService bean or other things?

**Comment by Manokethan** [comment]
Otherwise, your questions are correct and make me thing. I do not know about the initial plans of this project. Is it possible to have the acceptance list? 

I am thinking of:
- creating an external quartz project scheduler launchable / deployable separately from SCDF
- it will have an api rest that would manage the crons.
- it would use spring-cloud-dataflow-rest-client to launch the tasks
- the implementation of the scheduler interface could be summed up by calling the api rest of the external scehduler to manage the crons

What do you think ?

**Comment by aritzbastida** [comment]
Hi! I'm reviewing the PR and I've got some doubts. Does the code work as-is? 
To make it work, I miss some pieces in spring-cloud-dataflow-server-local-autoconfig project, which, of course, belong to another repo. 

I've done some tweaking on my own, and it almost works, but I've got some concerns right now:
* No Quartz starter in Spring Boot 1.5.14, so I had to backport the code from Spring Boot 2. This code should be kept until SCDF 2, I guess.
* If I change the store to JDBC, then I get the following exception: 
`java.io.NotSerializableException: Unable to serialize JobDataMap for insertion into database because the value of property 'taskRequest' is not serializable: org.springframework.cloud.deployer.spi.core.AppDeploymentRequest`

**Comment by Manokethan** [comment]
Hi,

sorry, I did not commit but indeed, I had problems when I moved to an external database that I have since corrected. I commited all the fixes.

Could you try again? To facilitate your tests; you will find in my repo https://github.com/Manokethan/spring-cloud-dataflow/commit/117c6c3eb4d083bff5452faf9ec3a5b248c0bca8 the configuration that I use to make everything work. Like you, I had to backport the code from Spring Boot 2 waiting for version 2.0 of spring-cloud-dataflow.

Depending on which database you use, you may need to configure spring.cloud.scheduler.quartz.properties.org.quartz.jobStore.driverDelegateClass. Using the postgresql database, I set this property to org.quartz.impl.jdbcjobstore.PostgreSQLDelegate. You will find the different posibilities in the quartz documentation.

For the moment I have not noticed any problem. It has been running for two weeks with a task running every 10 seconds.

**Comment by aritzbastida** [comment]
HI @Manokethan!! Thanks for the commit! I can confirm that it also works in my environment, storing the Quartz metadata in an Oracle database.  :-)

**Comment by bruhalm** [comment]
Is this going to get merged in anytime soon?

**Comment by gdubya** [comment]
Also interested in updates to this PR

**Comment by bruhalm** [comment]
I forked the pull request and updated for cloud data flow 2.0...only one minor change. I can send a PR if its going to get merged in.

**Comment by thienbaole** [comment]
Can we also override the scheduler in Pivotal Cloud Foundry with this Quarzt Scheduler?

**Comment by sunilr1990** [comment]
How can we integrate this to application ?

**Comment by duyetphamm** [comment]
HI @Manokethan @aritzbastida, i have tested the scheduler. However, I got an error that "Could not find a default scheduler spring cloud". Do you have any ideas about this problem?

**Comment by sabbyanandan** [comment]
Hi, folks! Thank you for your interest in this library. Unfortunately, we aren't going to be able to support a Quartz-based local implementation of Scheduler in SCDF at the time of this writing. Here are some thoughts that I shared in a [Gitter thread](https://gitter.im/spring-cloud/spring-cloud-dataflow?at=5df2541055d9392300faf3c9) recently — just quoting the same.

> "It is a common practice for folks to rely on an enterprise scheduler in a production setting. In K8s, we rely on the scheduler agent in Kubernetes itself — assuming users would use a production-ready K8s cluster. Likewise, in CF, we rely on pcf-scheduler, which is a managed service in Cloud Foundry.
> 
> However, in local, there's no platform-like concept attached to it. SCDF is a Boot app that runs as a local Java process in the VM or in the Docker Deamon (if you're using Docker Compose).
> 
> All that said, the quality of service and resilient operations are limited in the local method. If something goes wrong or if SCDF app crashes, there's nothing to bring it back up automatically. It is your responsibility to manage and operate it reliably — that's why it is typically used for local development.
> 
> Given these limitations, we didn't want to take upon the local-scheduler in our releases. If you're going to need a Scheduler in local-mode, it is a common practice to use quartz-based implementation locally. It will be a simple Boot app, too. There are many Boot + Quartz examples you can find online."

**Pull request closed without merging**
